-- V2: Safety net — create tables if V1 failed silently on H2
CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author_name VARCHAR(255) NOT NULL,
    cover_image VARCHAR(1024),
    about_description TEXT,
    author_true_story TEXT,
    difficulty_level VARCHAR(50),
    length_label VARCHAR(255),
    language_tone VARCHAR(255),
    what_to_expect TEXT,
    how_not_to_judge TEXT,
    expected_outcome TEXT,
    expected_time_investment DOUBLE PRECISION,
    our_rating INTEGER,
    verdict VARCHAR(50),
    confidence_percentage INTEGER,
    estimated_roi VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS book_categories (
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, category_id)
);

CREATE TABLE IF NOT EXISTS book_verdict_reasons (
    book_id BIGINT NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    reason TEXT
);

CREATE TABLE IF NOT EXISTS external_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT REFERENCES books(id) ON DELETE CASCADE,
    label VARCHAR(255) NOT NULL,
    url VARCHAR(1024) NOT NULL
);

CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    message TEXT NOT NULL,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed admin (only if empty)
INSERT INTO admin_users (username, password, role)
SELECT 'admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ROLE_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM admin_users WHERE username = 'admin');

-- Categories (only if empty)
MERGE INTO categories (id, name) KEY(id)
VALUES (1,'Business'), (2,'Philosophy'), (3,'Fiction'), (4,'Self-Help'), (5,'History'), (6,'Science'), (7,'Psychology');

-- ═══ 10 BOOKS ════════════════════════════════════════════════════════════

-- 1. Atomic Habits
MERGE INTO books (id, title, author_name, cover_image, about_description, author_true_story,
  difficulty_level, length_label, language_tone, what_to_expect, how_not_to_judge,
  expected_outcome, expected_time_investment, our_rating, verdict, confidence_percentage, estimated_roi)
KEY(id) VALUES (
  1, 'Atomic Habits', 'James Clear',
  'https://m.media-amazon.com/images/I/81bGKUa1e0L._AC_UF1000,1000_QL80_.jpg',
  'A scientifically backed, deeply practical guide to building good habits and breaking bad ones through tiny, 1% improvements every day. James Clear distills decades of research into a four-step loop — cue, craving, response, reward — and shows how to engineer your environment, identity, and routines to make change effortless.',
  'James Clear was hit in the face by a baseball bat during a high-school game, suffering a fractured skull. His long recovery forced him to rely on small, consistent habits to rebuild strength and coordination. He later became a competitive weightlifter by applying the same principles, and started blogging about habit formation before this book exploded into a global phenomenon.',
  'EASY', '320 pages', 'Actionable, Direct, Clear',
  'A step-by-step framework: the four laws of behavior change. Expect concrete tactics — habit stacking, implementation intentions, temptation bundling, and designing your environment. No filler chapters.',
  'Do not judge it as motivational fluff. It is a systems-design manual for human behavior. The title is literal: "atomic" means both tiny and foundational — not "nuclear-strength". Expect a reference manual, not a one-read wonder.',
  'A permanent shift in how you think about change. You will audit your environment differently, notice habit loops you were blind to, and have a concrete vocabulary for designing daily routines.',
  6.5, 5, 'YES', 95, 'Very High — saves months of wasted trial-and-error'
);
MERGE INTO book_categories (book_id, category_id) KEY(book_id, category_id) VALUES (1, 4), (1, 1);
MERGE INTO book_verdict_reasons (book_id, reason) KEY(book_id, reason)
VALUES (1, 'The most actionable habit book ever written — frameworks actually work in real life.'),
       (1, 'Permanent mental model shift on identity-based behavior change.'),
       (1, 'Avoids fluff entirely; every page earns its place.');
MERGE INTO external_links (id, book_id, label, url) KEY(id) VALUES (1, 1, 'Amazon', 'https://www.amazon.com/Atomic-Habits-Proven-Build-Break/dp/0735211299');

-- 2. Thinking, Fast and Slow
MERGE INTO books (id, title, author_name, cover_image, about_description, author_true_story,
  difficulty_level, length_label, language_tone, what_to_expect, how_not_to_judge,
  expected_outcome, expected_time_investment, our_rating, verdict, confidence_percentage, estimated_roi)
KEY(id) VALUES (
  2, 'Thinking, Fast and Slow', 'Daniel Kahneman',
  'https://m.media-amazon.com/images/I/71f6Dcg9ENL._AC_UF1000,1000_QL80_.jpg',
  'A Nobel laureate psychologist reveals the two systems that drive the way we think: System 1 (fast, intuitive, emotional) and System 2 (slow, deliberative, logical). Kahneman unpacks cognitive biases — anchoring, availability heuristic, loss aversion — that shape every decision we make, often without our awareness.',
  'Daniel Kahneman won the Nobel Prize in Economics despite being a psychologist, because his behavioral economics research (done with his lifelong collaborator Amos Tversky) fundamentally overturned rational-agent theory. Tversky died before the Nobel was awarded; Kahneman has said the prize should have been shared.',
  'CHALLENGING', '499 pages', 'Academic, Dense, Fascinating',
  'Dense, research-heavy chapters. Expect statistical concepts, clinical studies, and deep analysis of human error. The book is structured as a journey, but each chapter stands alone. Plan to read slowly.',
  'Do not expect a light beach read. It requires active concentration. Also do not expect prescriptions — Kahneman is honest that knowing about biases barely helps you avoid them.',
  'You will recognize cognitive biases in yourself, in news media, in financial decisions. A fundamental vocabulary upgrade for any serious thinker.',
  15.0, 4, 'CONDITIONAL', 80, 'Moderate — essential knowledge, but takes real effort to internalize'
);
MERGE INTO book_categories (book_id, category_id) KEY(book_id, category_id) VALUES (2, 7), (2, 1);
MERGE INTO book_verdict_reasons (book_id, reason) KEY(book_id, reason)
VALUES (2, 'Incredible, paradigm-shifting insights into human irrationality.'),
       (2, 'Can be very dense and academic — requires patience.'),
       (2, 'Worth reading slowly rather than racing through it.');
MERGE INTO external_links (id, book_id, label, url) KEY(id) VALUES (2, 2, 'Amazon', 'https://www.amazon.com/Thinking-Fast-Slow-Daniel-Kahneman/dp/0374533555');

-- 3. Dune
MERGE INTO books (id, title, author_name, cover_image, about_description, author_true_story,
  difficulty_level, length_label, language_tone, what_to_expect, how_not_to_judge,
  expected_outcome, expected_time_investment, our_rating, verdict, confidence_percentage, estimated_roi)
KEY(id) VALUES (
  3, 'Dune', 'Frank Herbert',
  'https://m.media-amazon.com/images/I/81ym3QUd3KL._AC_UF1000,1000_QL80_.jpg',
  'Set on the desert planet Arrakis, Dune tells the story of Paul Atreides as his noble family is thrust into a brutal political struggle for control of the most valuable substance in the galaxy — spice melange. A sweeping epic of political intrigue, religion, ecology, and human destiny that reshaped the entire science-fiction genre.',
  'Frank Herbert was a journalist researching sand dunes in Oregon for a magazine article about the USDA''s project to stop the dunes'' spread. The article was never published, but his obsession with ecology deepened into a 6-year research project that became Dune. It was rejected by 23 publishers before being accepted — by a car-manual publisher.',
  'CHALLENGING', '896 pages', 'Epic, Atmospheric, Complex',
  'Immersive world-building so deep it has its own glossary. Slow opening 100 pages that reward patience. Political intrigue, philosophical musings, and multiple POV characters. Not a plot-driven thriller.',
  'Do not judge it like a plot-driven action novel. The first 100 pages are setup-heavy. Do not compare it to the films — the book goes far deeper into Paul''s prescient consciousness and the political machinations.',
  'An appreciation for one of the foundational texts of modern science fiction. A new framework for thinking about ecology, power, and the danger of charismatic leaders.',
  25.0, 5, 'YES', 95, 'High — profound cultural literacy and lifelong reference point'
);
MERGE INTO book_categories (book_id, category_id) KEY(book_id, category_id) VALUES (3, 3);
MERGE INTO book_verdict_reasons (book_id, reason) KEY(book_id, reason)
VALUES (3, 'Unmatched world-building — ecology, religion, and politics woven into one epic.'),
       (3, 'Explores timeless themes of power, messiahs, and ecological collapse.'),
       (3, 'The foundational science-fiction novel — cultural literacy alone makes it worth it.');
MERGE INTO external_links (id, book_id, label, url) KEY(id) VALUES (3, 3, 'Amazon', 'https://www.amazon.com/Dune-Frank-Herbert/dp/0441172717');

-- 4. Sapiens
MERGE INTO books (id, title, author_name, cover_image, about_description, author_true_story,
  difficulty_level, length_label, language_tone, what_to_expect, how_not_to_judge,
  expected_outcome, expected_time_investment, our_rating, verdict, confidence_percentage, estimated_roi)
KEY(id) VALUES (
  4, 'Sapiens: A Brief History of Humankind', 'Yuval Noah Harari',
  'https://m.media-amazon.com/images/I/713jIoMO3UL._AC_UF1000,1000_QL80_.jpg',
  'A sweeping narrative from the Stone Age to the 21st century asking one deceptively simple question: what made Homo sapiens the dominant species on Earth? Harari''s answer — our unique ability to believe in shared myths like nations, money, and corporations — is simultaneously humbling and thrilling.',
  'Harari originally wrote this in Hebrew as a university history textbook. When it became a surprise bestseller in Israel, he expanded and translated it. Barack Obama, Bill Gates, and Mark Zuckerberg have all publicly recommended it, launching it to 25 million+ copies sold worldwide.',
  'MODERATE', '464 pages', 'Engaging, Provocative, Broad',
  'Sweeping historical narratives told at 10,000-foot altitude. Challenging, sometimes uncomfortable, assertions about human nature. Not a peer-reviewed text — it synthesizes widely. Some chapters hit harder than others.',
  'Do not expect academic rigor or footnoted citations for every claim. Harari is a storyteller with a thesis, not a historian presenting a case. Take his provocations as invitations to think, not conclusions to accept.',
  'A unified, macro-perspective on human history. You will see money, religion, and empire completely differently.',
  12.0, 5, 'YES', 85, 'High — changes how you see civilization itself'
);
MERGE INTO book_categories (book_id, category_id) KEY(book_id, category_id) VALUES (4, 5);
MERGE INTO book_verdict_reasons (book_id, reason) KEY(book_id, reason)
VALUES (4, 'Brilliantly connects the Agricultural Revolution to modern capitalism in one coherent story.'),
       (4, 'The "shared myths" thesis alone is worth the price.'),
       (4, 'Written for a general audience — accessible and engaging throughout.');
MERGE INTO external_links (id, book_id, label, url) KEY(id) VALUES (4, 4, 'Amazon', 'https://www.amazon.com/Sapiens-Humankind-Yuval-Noah-Harari/dp/0062316095');

-- 5. Meditations
MERGE INTO books (id, title, author_name, cover_image, about_description, author_true_story,
  difficulty_level, length_label, language_tone, what_to_expect, how_not_to_judge,
  expected_outcome, expected_time_investment, our_rating, verdict, confidence_percentage, estimated_roi)
KEY(id) VALUES (
  5, 'Meditations', 'Marcus Aurelius',
  'https://m.media-amazon.com/images/I/81c2P6Bbn8L._AC_UF1000,1000_QL80_.jpg',
  'The private journal of a Roman Emperor — the most powerful man in the world at the height of Roman civilization — recording his daily Stoic philosophy practice. Written entirely for himself with no intention of publication, it is the most honest and intimate account of a leader''s inner struggle ever committed to paper.',
  'Marcus Aurelius governed Rome from 161 to 180 AD during a period of constant warfare (the Marcomannic Wars) and devastating plague. He wrote these reflections while on military campaigns, in command of half a million soldiers. He never intended them to be read by anyone else — which is why they''re so brutally honest.',
  'MODERATE', '254 pages', 'Aphoristic, Reflective, Ancient',
  'Short, standalone passages — some a sentence, some a paragraph. No narrative arc. Best read slowly, one passage per day. Expect repetition of themes: impermanence, duty, emotional control, and the dichotomy of control.',
  'Do not expect a structured philosophical treatise. It is fragmentary and repetitive by nature — these are daily journal entries, not published essays. Also: some translations are radically different; the Gregory Hays (Modern Library) translation is by far the most readable.',
  'A robust, time-tested mental framework for dealing with adversity, loss, anger, and uncertainty — from someone who faced all of them at scale.',
  6.0, 5, 'YES', 97, 'Extremely High — 2,000-year-old wisdom that applies to every single day'
);
MERGE INTO book_categories (book_id, category_id) KEY(book_id, category_id) VALUES (5, 2);
MERGE INTO book_verdict_reasons (book_id, reason) KEY(book_id, reason)
VALUES (5, 'The most honest and practical philosophy book ever written — from a man with everything at stake.'),
       (5, '2,000-year-old wisdom that reads like it was written this morning.'),
       (5, 'The Gregory Hays translation (Modern Library) is essential — do not pick up a Victorian version.');
MERGE INTO external_links (id, book_id, label, url) KEY(id) VALUES (5, 5, 'Amazon', 'https://www.amazon.com/Meditations-New-Translation-Marcus-Aurelius/dp/0812968255');

-- 6. The Subtle Art of Not Giving a F*ck
MERGE INTO books (id, title, author_name, cover_image, about_description, author_true_story,
  difficulty_level, length_label, language_tone, what_to_expect, how_not_to_judge,
  expected_outcome, expected_time_investment, our_rating, verdict, confidence_percentage, estimated_roi)
KEY(id) VALUES (
  6, 'The Subtle Art of Not Giving a F*ck', 'Mark Manson',
  'https://m.media-amazon.com/images/I/71QKQ9mwV7L._AC_UF1000,1000_QL80_.jpg',
  'A counterintuitive self-help guide arguing that the key to a good life is not caring about everything — but rather choosing very deliberately what you do care about. Manson argues that modern "positive thinking" culture is toxic, and that embracing pain, failure, and uncertainty is the only path to genuine meaning.',
  'Mark Manson started as a pickup artist blogger who evolved into a personal development writer when he realized most self-help advice was superficial. He packaged Stoic and existentialist philosophy in a profane, conversational voice that resonated with a generation exhausted by toxic positivity.',
  'EASY', '224 pages', 'Irreverent, Honest, Conversational',
  'Humorous, story-driven chapters. Profane language throughout. Surprisingly thoughtful philosophy beneath the brash exterior. A quick read — 4-5 hours. Best consumed in one or two sessions.',
  'Do not dismiss it because of the title or the language. It is actually a modern repackaging of Stoicism and Existentialism. Do not read it expecting life advice you''ve never heard before — the ideas aren''t new, the delivery is.',
  'A useful recalibration of your priorities. You will question which things you actually care about vs. which things you feel culturally obligated to care about.',
  4.5, 4, 'YES', 88, 'High — fast read, genuine perspective shift'
);
MERGE INTO book_categories (book_id, category_id) KEY(book_id, category_id) VALUES (6, 4);
MERGE INTO book_verdict_reasons (book_id, reason) KEY(book_id, reason)
VALUES (6, 'A refreshing antidote to toxic positivity culture.'),
       (6, 'Quick, genuinely funny, and surprisingly deep in places.'),
       (6, 'Accessible entry point to Stoic ideas for readers who find philosophy books dry.');
MERGE INTO external_links (id, book_id, label, url) KEY(id) VALUES (6, 6, 'Amazon', 'https://www.amazon.com/Subtle-Art-Not-Giving-Counterintuitive/dp/0062457713');

-- 7. Zero to One
MERGE INTO books (id, title, author_name, cover_image, about_description, author_true_story,
  difficulty_level, length_label, language_tone, what_to_expect, how_not_to_judge,
  expected_outcome, expected_time_investment, our_rating, verdict, confidence_percentage, estimated_roi)
KEY(id) VALUES (
  7, 'Zero to One', 'Peter Thiel',
  'https://m.media-amazon.com/images/I/71RY1L6SmRL._AC_UF1000,1000_QL80_.jpg',
  'Peter Thiel''s contrarian startup philosophy, based on his Stanford lectures. His central thesis: going from 0 to 1 (creating something genuinely new) is infinitely harder and more valuable than going from 1 to n (copying existing models). He argues monopolies are good, competition is for losers, and that most "disruptive" companies aren''t really creating anything new.',
  'Thiel co-founded PayPal, became the first outside investor in Facebook (buying 10% for $500k), and later founded Palantir. He was the first venture capitalist to publicly back Donald Trump in 2016. Love him or hate him, his track record of contrarian bets is extraordinary.',
  'EASY', '195 pages', 'Contrarian, Dense with Ideas, Direct',
  'A short book packed with provocative assertions. Each chapter centers on a bold claim. Not a how-to guide — more a philosophical framework for ambitious thinkers. Some chapters hit harder than others.',
  'Do not judge it by whether you agree with Thiel politically. The business insights stand entirely on their own. Also do not expect operational startup advice — this is strategic and philosophical, not tactical.',
  'A fundamentally different lens for evaluating business ideas. You will stop admiring "competition" and start asking: what valuable company is nobody building?',
  4.0, 4, 'YES', 85, 'High — concise and full of ideas you won''t find in typical business books'
);
MERGE INTO book_categories (book_id, category_id) KEY(book_id, category_id) VALUES (7, 1);
MERGE INTO book_verdict_reasons (book_id, reason) KEY(book_id, reason)
VALUES (7, 'Contrarian ideas that genuinely make you question consensus thinking.'),
       (7, 'Extremely short — reads in a single evening, delivers lasting impact.'),
       (7, 'The "last mover advantage" and "secrets" chapters alone justify reading it.');
MERGE INTO external_links (id, book_id, label, url) KEY(id) VALUES (7, 7, 'Amazon', 'https://www.amazon.com/Zero-One-Notes-Startups-Future/dp/0804139296');

-- 8. Man''s Search for Meaning
MERGE INTO books (id, title, author_name, cover_image, about_description, author_true_story,
  difficulty_level, length_label, language_tone, what_to_expect, how_not_to_judge,
  expected_outcome, expected_time_investment, our_rating, verdict, confidence_percentage, estimated_roi)
KEY(id) VALUES (
  8, 'Man''s Search for Meaning', 'Viktor Frankl',
  'https://m.media-amazon.com/images/I/61157nSQEAL._AC_UF1000,1000_QL80_.jpg',
  'A psychiatrist''s account of surviving four Nazi concentration camps — including Auschwitz — and the psychological framework (Logotherapy) he developed from observing what separated those who survived mentally from those who didn''t. The core insight: meaning, not pleasure or power, is the primary human motivational force.',
  'Viktor Frankl was a Viennese psychiatrist who had already developed the foundations of Logotherapy before the war. He, his wife, and his parents were deported to camps in 1942. He survived; most of his family did not. He wrote the first draft of this book in nine days after liberation, intentionally published anonymously because he thought no one would care.',
  'EASY', '165 pages', 'Profound, Personal, Direct',
  'Part memoir, part philosophy. The first half is an account of camp life — brutal, unflinching, but never gratuitous. The second half explains Logotherapy. It is a very short book — readable in a single afternoon.',
  'Do not approach it as a Holocaust history text. It is a psychological and philosophical inquiry into meaning. The suffering is the context, not the subject.',
  'A permanently altered relationship with suffering and purpose. You will ask "why" before you ask "how" in difficult situations. One of the most life-changing short books ever written.',
  3.0, 5, 'YES', 99, 'Incalculably High — one of the most important books ever written'
);
MERGE INTO book_categories (book_id, category_id) KEY(book_id, category_id) VALUES (8, 2), (8, 7);
MERGE INTO book_verdict_reasons (book_id, reason) KEY(book_id, reason)
VALUES (8, 'The most important book on meaning and suffering ever written — full stop.'),
       (8, 'Absurdly short for how much it changes you. A single afternoon investment.'),
       (8, 'Reframes every personal hardship you will ever face.');
MERGE INTO external_links (id, book_id, label, url) KEY(id) VALUES (8, 8, 'Amazon', 'https://www.amazon.com/Mans-Search-Meaning-Viktor-Frankl/dp/0807014273');

-- 9. The Psychology of Money
MERGE INTO books (id, title, author_name, cover_image, about_description, author_true_story,
  difficulty_level, length_label, language_tone, what_to_expect, how_not_to_judge,
  expected_outcome, expected_time_investment, our_rating, verdict, confidence_percentage, estimated_roi)
KEY(id) VALUES (
  9, 'The Psychology of Money', 'Morgan Housel',
  'https://m.media-amazon.com/images/I/71g2ednj0JL._AC_UF1000,1000_QL80_.jpg',
  'A collection of 19 short stories exploring the strange and counterintuitive ways people think about money. Housel argues that financial success has less to do with intelligence or access to information and more to do with behavior, temperament, and long time-horizons. The most underrated personal finance book of the decade.',
  'Morgan Housel is a former Wall Street Journal columnist who became a partner at the Collaborative Fund. He started writing this book as a memo that went viral in the investing community. He deliberately wrote it as standalone essays rather than a linear argument, which is why it is so re-readable.',
  'EASY', '256 pages', 'Conversational, Storytelling, Insightful',
  'Short, self-contained chapters — each a standalone essay with a single core idea. Stories from history woven into practical insight. No spreadsheets, no financial formulas. Accessible to anyone.',
  'Do not expect specific investment advice or asset allocation strategies. This is behavioral finance, not financial planning. Do not read it for a "system" — read it for a worldview.',
  'A completely different relationship with risk, wealth, and long-term thinking. You will stop comparing your portfolio to others and start asking if your financial behavior matches your actual goals.',
  5.0, 5, 'YES', 93, 'Very High — behavioral shift that compounds over your lifetime'
);
MERGE INTO book_categories (book_id, category_id) KEY(book_id, category_id) VALUES (9, 1), (9, 7);
MERGE INTO book_verdict_reasons (book_id, reason) KEY(book_id, reason)
VALUES (9, 'The best explanation of why smart people make terrible financial decisions.'),
       (9, 'Story-driven and effortlessly readable — no finance background needed.'),
       (9, 'The chapter on "room for error" alone is worth the price of the book.');
MERGE INTO external_links (id, book_id, label, url) KEY(id) VALUES (9, 9, 'Amazon', 'https://www.amazon.com/Psychology-Money-Timeless-lessons-happiness/dp/0857197681');

-- 10. Project Hail Mary
MERGE INTO books (id, title, author_name, cover_image, about_description, author_true_story,
  difficulty_level, length_label, language_tone, what_to_expect, how_not_to_judge,
  expected_outcome, expected_time_investment, our_rating, verdict, confidence_percentage, estimated_roi)
KEY(id) VALUES (
  10, 'Project Hail Mary', 'Andy Weir',
  'https://m.media-amazon.com/images/I/811mXzGeE2L._AC_UF1000,1000_QL80_.jpg',
  'A lone astronaut wakes up with amnesia on a spaceship millions of miles from Earth. He has no idea why he''s there. As his memory returns, he realizes he is humanity''s last hope against an extinction-level threat to the Sun. A masterpiece of hard science fiction that is also, somehow, a joyful and profoundly moving story of friendship.',
  'Andy Weir wrote The Martian as a free blog serial, self-published it for 99 cents, then watched it become a Ridley Scott film. Project Hail Mary took 5 years to write. He validated every single scientific concept in the book against actual physics and biology, consulting researchers to ensure even the alien biology was plausible.',
  'EASY', '476 pages', 'Fast-Paced, Scientific, Joyful',
  'A page-turner from page one, even though the setup is deliberately mysterious. Lots of science problem-solving that reads like watching someone crack a puzzle in real time. The alien relationship develops slowly and pays off enormously.',
  'Do not be put off by the science — it is explained in a way that makes you feel clever for following it. Do not read the back cover or any review that hints at the plot twist.',
  'Pure, elated, reading joy. This is the rare book that makes you feel good about being a human and about science. One of the most purely entertaining books of the decade.',
  14.0, 5, 'YES', 92, 'High — 14 hours of the best entertainment hard sci-fi can offer'
);
MERGE INTO book_categories (book_id, category_id) KEY(book_id, category_id) VALUES (10, 3), (10, 6);
MERGE INTO book_verdict_reasons (book_id, reason) KEY(book_id, reason)
VALUES (10, 'The most genuinely joyful reading experience in modern science fiction.'),
       (10, 'The alien relationship is unlike anything else in the genre.'),
       (10, 'Hard science that is completely accessible — makes you feel like a scientist.');
MERGE INTO external_links (id, book_id, label, url) KEY(id) VALUES (10, 10, 'Amazon', 'https://www.amazon.com/Project-Hail-Mary-Andy-Weir/dp/0593135202');
